### ISSUE TITLE
Can you explain how to run this file

### ISSUE THREAD

**Issue by skapoor2024** [hwanython/HanSeg_2023#1]
Please could you explain how to run this model for training. Do we need to directly put the training dataset provided. Or do we have to preprocess. What parameters go to train.py file

**Comment by hwanython** [comment]
Hi there,

Thank you so much for taking an interest in my repository. I'm currently in the midst of developing the code. As it stands, the project is still a work in progress and isn't fully functional yet.

I've designed the system with simplicity in mind: all parameters are set in the config.yaml file. This means that when you run train.py, it only requires the configuration file. This config file includes all necessary details, such as the dataset path and training parameters.

I'm working diligently to complete it as soon as possible. I appreciate your patience and interest in this project!

Best regards,
